{
 "title": "Opentsdb",
 "tags": [ "Opentsdb" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "JvmMemoryUesd",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tsd_jvm_ramused/(tsd_jvm_ramused+tsd_jvm_ramfree)*100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ServiceCount",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "sum(tsd_active)" }
   ]
  },
  {
   "title": "RequestPreMinute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tsd_hbase_rpcs[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "OpenConnectCount",
   "type": "graph",
   "description": "连接开启数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tsd_connectionmgr_connections{type=\"open\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "tsd_connectionmgr_connections{type=\"timeout\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ExceptionCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tsd_connectionmgr_exceptions[1m])",
     "legendFormat": "{{host}}-{{type}}"
    }
   ]
  },
  {
   "title": "HttpCallTime(95%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tsd_http_latency_95pct{type=\"all\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HbaseRequestCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tsd_hbase_rpcs[5m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(tsd_hbase_rpcs_batched[5m]))",
     "legendFormat": "batched"
    }
   ]
  },
  {
   "title": "ErrorCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tsd_rpc_errors[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QueryEndpointRequest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tsd_http_query_success[1m])",
     "legendFormat": "{{host}}-success"
    },
    {
     "expr": "irate(tsd_http_query_invalid_requests[1m])",
     "legendFormat": "{{host}}-invalid"
    },
    {
     "expr": "irate(tsd_http_query_exceptions[1m])",
     "legendFormat": "{{host}}-exceptions"
    }
   ]
  },
  {
   "title": "StorageCommandError",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tsd_compaction_errors[1m])) by (rpc)",
     "legendFormat": "{{rpc}}"
    }
   ]
  }
 ]
}